global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tlscheck'

scrape_configs:
  - job_name: 'tlscheck-api'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['tlscheck:3000']
    # authorization:
    #   credentials: '${METRICS_API_KEY}'
